language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t davidalba/react-test .

script:
  - docker run -e CI=true davidalba/react-test npm run test

after_success:
  - docker build -t davidalba/multi-client ./client
  - docker build -t davidalba/multi-nginx ./nginx
  - docker build -t davidalba/multi-server ./server
  - docker build -t davidalba/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidalba/multi-client
  - docker push davidalba/multi-nginx
  - docker push davidalba/multi-server
  - docker push davidalba/multi-worker

#deploy:
# provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-east-2-348179825777"
#  bucket_path: "docker"
#  access_key_id:
#    secure: $AWS_ACCESS_KEY 
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
#  on:
#    branch: master